auth0:
  audience: smartshare-api
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://smartshare.eu.auth0.com/
---
spring:
  profiles: dev
routes:
  servers:
    - name: coreserver
      uri: http://localhost:8084
    - name: administrationserver
      uri: http://localhost:8085
    - name: lockserver
      uri: http://localhost:8083
---

spring:
  profiles: prod
routes:
  servers:
    - name: coreserver
      uri: ${CORE_SERVER_URL}
    - name: administrationserver
      uri: ${ADMINISTRATION_SERVER_URL}
    - name: lockserver
      uri: ${LOCK_SERVER_URL}